elasticsearch:
  image: elasticsearch:5
  environment:
    ES_JAVA_OPTS: -Xms1g -Xmx1g
    discovery.zen.ping.unicast.hosts: elasticsearch
    cluster.name: es
    network.host: 0.0.0.0
    discovery.zen.minimum_master_nodes: '1'
  stdin_open: true
  volumes:
  - /usr/share/elasticsearch/data
  tty: true
  labels:
    container_group: logging
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
kopf:
  image: rancher/kopf:v0.4.0
  environment:
    KOPF_SERVER_NAME: es.dev
    KOPF_ES_SERVERS: elasticsearch:9200
  stdin_open: true
  tty: true
  links:
  - elasticsearch:elasticsearch
  labels:
    container_group: logging
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
logstash-indexer-config:
  restart: always
  image: rancher/logstash-config:v0.2.0
  labels:
    io.rancher.container.hostname_override: container_name
    container_group: logging
redis:
  restart: always
  tty: true
  image: redis:3.2.6-alpine
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
    container_group: logging
logstash-indexer:
  restart: always
  tty: true
  volumes_from:
  - logstash-indexer-config
  command:
  - logstash
  - -f
  - /etc/logstash
  image: logstash:5.1.1-alpine
  links:
  - redis:redis
  - elasticsearch:elasticsearch
  stdin_open: true
  labels:
    io.rancher.sidekicks: logstash-indexer-config
    io.rancher.container.hostname_override: container_name
    container_group: logging
logstash-collector-config:
  restart: always
  image: rancher/logstash-config:v0.2.0
  labels:
    io.rancher.container.hostname_override: container_name
    container_group: logging
logstash-collector:
  restart: always
  tty: true
  links:
  - redis:redis
  volumes_from:
  - logstash-collector-config
  command:
  - logstash
  - -f
  - /etc/logstash
  image: logstash:5.1.1-alpine
  stdin_open: true
  labels:
    io.rancher.sidekicks: logstash-collector-config
    io.rancher.container.hostname_override: container_name
    container_group: logging
kibana:
  image: kibana:5
  environment:
    SERVER_PORT: '5601'
    SERVER_HOST: “0.0.0.0
    ELASTICSEARCH_URL: http://elasticsearch:9200
  stdin_open: true
  tty: true
  links:
  - elasticsearch:elasticsearch
  labels:
    container_group: logging
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always

prometheus:
  image: prom/prometheus:v1.4.1
  tty: true
  links:
  - alertmanager:alertmanager
  - cadvisor:cadvisor
  - node-exporter:node-exporter
  volumes_from:
  - prom-conf
  command:
  - -alertmanager.url=http://alertmanager:9093
  - -config.file=/etc/prom-conf/prometheus.yml
  - -storage.local.path=/prometheus
  - -web.console.libraries=/etc/prometheus/console_libraries
  - -web.console.templates=/etc/prometheus/consoles
  labels:
    io.rancher.sidekicks: prom-conf
    container_group: monitoring
prom-conf:
  image: infinityworks/prom-conf:17
  net: none
  volumes:
  - /etc/prom-conf/
  tty: true
  links:
  - alertmanager:alertmanager
  - cadvisor:cadvisor
  - node-exporter:node-exporter
  labels:
    container_group: monitoring
node-exporter:
  image: prom/node-exporter:latest
  stdin_open: true
  tty: true
  labels:
    container_group: monitoring
    io.rancher.scheduler.global: 'true'
cadvisor:
  image: google/cadvisor:latest
  stdin_open: true
  volumes:
  - /:/rootfs:ro
  - /var/run:/var/run:rw
  - /sys:/sys:ro
  - /var/lib/docker/:/var/lib/docker:ro
  tty: true
  labels:
    container_group: monitoring
    io.rancher.scheduler.global: 'true'
grafana:
  image: grafana/grafana:4.2.0
  tty: true
  links:
  - prometheus:prometheus
  volumes_from:
  - graf-db
  labels:
    io.rancher.sidekicks: graf-db
    container_group: monitoring
graf-db:
  image: infinityworks/graf-db:10
  net: none
  volumes:
  - /var/lib/grafana/
  tty: true
  links:
  - prometheus:prometheus
  command:
  - cat

elastalert:
  image: balleddog/elastalert
  environment:
    ELASTICSEARCH_HOST: elasticsearch
  stdin_open: true
  tty: true
  links:
  - elasticsearch:elasticsearch
  labels:
    io.rancher.container.pull_image: always
    container.group: alerting
alertmanager:
  image: prom/alertmanager:v0.5.0
  stdin_open: true
  tty: true
  labels:
    container_group: alerting
    io.rancher.container.pull_image: always
