prometheus:
  image: prom/prometheus:v1.4.1
  tty: true
  links:
  - alertmanager:alertmanager
  - cadvisor:cadvisor
  - node-exporter:node-exporter
  volumes_from:
  - prom-conf
  command:
  - -alertmanager.url=http://alertmanager:9093
  - -config.file=/etc/prom-conf/prometheus.yml
  - -storage.local.path=/prometheus
  - -web.console.libraries=/etc/prometheus/console_libraries
  - -web.console.templates=/etc/prometheus/consoles
  labels:
    io.rancher.sidekicks: prom-conf
    container_group: monitoring
prom-conf:
  image: infinityworks/prom-conf:17
  net: none
  volumes:
  - /etc/prom-conf/
  tty: true
  links:
  - alertmanager:alertmanager
  - cadvisor:cadvisor
  - node-exporter:node-exporter
  labels:
    container_group: monitoring
node-exporter:
  image: prom/node-exporter:latest
  stdin_open: true
  tty: true
  labels:
    container_group: monitoring
    io.rancher.scheduler.global: 'true'
cadvisor:
  image: google/cadvisor:latest
  stdin_open: true
  volumes:
  - /:/rootfs:ro
  - /var/run:/var/run:rw
  - /sys:/sys:ro
  - /var/lib/docker/:/var/lib/docker:ro
  tty: true
  labels:
    container_group: monitoring
    io.rancher.scheduler.global: 'true'
grafana:
  image: grafana/grafana:4.2.0
  tty: true
  links:
  - prometheus:prometheus
  external_links:
  - ${elasticsearch_link}:elasticsearch
  volumes_from:
  - graf-db
  labels:
    io.rancher.sidekicks: graf-db
    container_group: monitoring
graf-db:
  image: infinityworks/graf-db:10
  net: none
  volumes:
  - /var/lib/grafana/
  tty: true
  links:
  - prometheus:prometheus
  command:
  - cat

elastalert:
  image: balleddog/elastalert
  environment:
    ELASTICSEARCH_HOST: elasticsearch
  stdin_open: true
  tty: true
  external_links:
  - ${elasticsearch_link}:elasticsearch
  labels:
    io.rancher.container.pull_image: always
    container.group: alerting
alertmanager:
  image: prom/alertmanager:v0.5.0
  stdin_open: true
  tty: true
  labels:
    container_group: alerting
    io.rancher.container.pull_image: always
