.catalog:
  name: "monitoring"
  version: "0.1"
  description: "Logging-Monitoring-Alerting"
  questions:
    - variable: "elasticsearch_link"
      description: |
        stack/service link or external service link to elasticsearch
        cluster.
      label: "Elasticsearch stack/service"
      default: "es/elasticsearch-clients"
      required: true
      type: "service"

node-exporter:
  start_on_create: true
prom-conf:
  scale: 1
  start_on_create: true
elastalert:
  scale: 1
  start_on_create: true
grafana:
  scale: 1
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 5000
    port: 3000
    unhealthy_threshold: 3
    interval: 5000
    strategy: recreate
cadvisor:
  start_on_create: true
prometheus:
  scale: 1
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 5000
    port: 9090
    unhealthy_threshold: 3
    interval: 5000
    strategy: recreate
graf-db:
  scale: 1
  start_on_create: true
alertmanager:
  scale: 1
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 9093
    unhealthy_threshold: 3
    initializing_timeout: 60000
    interval: 2000
    strategy: recreate
    reinitializing_timeout: 60000
