---
name: Monitoring
description: >
  Monitoring-Alerting Stack for SenseTime Container Infrastructure.
version: 0.1
category: Monitoring
maintainer: Arman <aerman@sensetime.com|balleddog@gmail.com>
license: Apache2
projectURL: https://github.com/balleddog/rancher-catalog
