---
name: LMA
description: >
  Monitoring-Logging-Alerting Stack for SenseTime Container Infrastructure.
version: 0.1
category: Logging
maintainer: Arman <aerman@sensetime.com|balleddog@gmail.com>
license: Apache2
projectURL: https://github.com/balleddog/rancher-catalog
